/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as CountersRouteImport } from './routes/counters'
import { Route as IndexRouteImport } from './routes/index'

const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CountersRoute = CountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counters': typeof CountersRoute
  '/tasks': typeof TasksRoute
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counters': typeof CountersRoute
  '/tasks': typeof TasksRoute
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counters': typeof CountersRoute
  '/tasks': typeof TasksRoute
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counters' | '/tasks' | '/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counters' | '/tasks' | '/tic-tac-toe'
  id: '__root__' | '/' | '/counters' | '/tasks' | '/tic-tac-toe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountersRoute: typeof CountersRoute
  TasksRoute: typeof TasksRoute
  TicTacToeRoute: typeof TicTacToeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counters': {
      id: '/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof CountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountersRoute: CountersRoute,
  TasksRoute: TasksRoute,
  TicTacToeRoute: TicTacToeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
