/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTicTacToeRouteImport } from './routes/_authed/tic-tac-toe'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedCountersRouteImport } from './routes/_authed/counters'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTicTacToeRoute = AuthedTicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCountersRoute = AuthedCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/counters': typeof AuthedCountersRoute
  '/tasks': typeof AuthedTasksRoute
  '/tic-tac-toe': typeof AuthedTicTacToeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/counters': typeof AuthedCountersRoute
  '/tasks': typeof AuthedTasksRoute
  '/tic-tac-toe': typeof AuthedTicTacToeRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/counters': typeof AuthedCountersRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/_authed/tic-tac-toe': typeof AuthedTicTacToeRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/counters' | '/tasks' | '/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/counters' | '/tasks' | '/tic-tac-toe' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/counters'
    | '/_authed/tasks'
    | '/_authed/tic-tac-toe'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tic-tac-toe': {
      id: '/_authed/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof AuthedTicTacToeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/counters': {
      id: '/_authed/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof AuthedCountersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCountersRoute: typeof AuthedCountersRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedTicTacToeRoute: typeof AuthedTicTacToeRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCountersRoute: AuthedCountersRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedTicTacToeRoute: AuthedTicTacToeRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
